services:
  - type: web
    name: flask-website
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    repo: https://github.com/vedanth2609/flask-website
